
### Students Index
GET http://localhost:3000/students
Content-Type: application/json

### Students Create
POST http://localhost:3000/students
Content-Type: application/json

{
"first_name": "",
"last_name": "",
"email": "",
"phone_number": "",
"short_bio": "",
"linkedin": "",
"twitter": "",
"website": "",
"online_resume": "",
"github": "",
"photo": ""
}

### Students Show
GET http://localhost:3000/students/1
Content-Type: application/json

### Students Update
PATCH http://localhost:3000/students/1
Content-Type: application/json

{
"first_name": "",
"last_name": "",
"email": "",
"phone_number": "",
"short_bio": "",
"linkedin": "",
"twitter": "",
"website": "",
"online_resume": "",
"github": "",
"photo": ""
}

### Students Destroy
DELETE http://localhost:3000/students/1
Content-Type: application/json


# Skill Model Requests
### INDEX REQUEST
GET http://localhost:3000/skills/2.json
Content-Type: application/json 

### SHOW REQUEST
GET http://localhost:3000/skills/show/4.json
Content-Type: application/json 

### CREATE REQUEST
POST http://localhost:3000/skills.json
Content-Type: application/json 

{
  "student_id": 1,
  "skill": "Driving"
}

### EDIT REQUEST
PATCH http://localhost:3000/skills/7.json
Content-Type: application/json 

{
  "skill": "Drifting"
}

### DESTROY REQUEST
DELETE http://localhost:3000/skills/7.json
Content-Type: application/json 


